gOtherText_NewName::
    .string "NEW NAME$"

gNameChoice_Green::
    .string "GREEN$"

gNameChoice_Red::
    .string "RED$"

gNameChoice_Leaf::
    .string "LEAF$"

gNameChoice_Fire::
    .string "FIRE$"

gNameChoice_Gary::
    .string "GARY$"

gNameChoice_Kaz::
    .string "KAZ$"

gNameChoice_Toru::
    .string "TORU$"

gNameChoice_Adrian::
    .string "ADRIAN$"

gNameChoice_Dorian::
    .string "DORIAN$"

gNameChoice_Rowan::
    .string "ROWAN$"

gNameChoice_Blaire::
    .string "BLAIRE$"

gNameChoice_Cedric::
    .string "CEDRIC$"

gNameChoice_Lucian::
    .string "LUCIAN$"

gNameChoice_Orion::
    .string "ORION$"

gNameChoice_Silas::
    .string "SILAS$"

gNameChoice_Ash::
    .string "ASH$"

gNameChoice_Kene::
    .string "KENE$"

gNameChoice_Geki::
    .string "GEKI$"

gNameChoice_Jak::
    .string "JAK$"

gNameChoice_Janne::
    .string "JANNE$"

gNameChoice_Jonn::
    .string "JONN$"

gNameChoice_Kamon::
    .string "KAMON$"

gNameChoice_Karl::
    .string "KARL$"

gNameChoice_Taylor::
    .string "TAYLOR$"

gNameChoice_Oscar::
    .string "OSCAR$"

gNameChoice_Hiro::
    .string "HIRO$"

gNameChoice_Max::
    .string "MAX$"

gNameChoice_Jon::
    .string "JON$"

gNameChoice_Ralph::
    .string "RALPH$"

gNameChoice_Kay::
    .string "KAY$"

gNameChoice_Tosh::
    .string "TOSH$"

gNameChoice_Roak::
    .string "ROAK$"

gNameChoice_Omi::
    .string "OMI$"

gNameChoice_Jodi::
    .string "JODI$"

gNameChoice_Amanda::
    .string "AMANDA$"

gNameChoice_Hillary::
    .string "HILLARY$"

gNameChoice_Makey::
    .string "MAKEY$"

gNameChoice_Michi::
    .string "MICHI$"

gNameChoice_Paula::
    .string "PAULA$"

gNameChoice_June::
    .string "JUNE$"

gNameChoice_Cassie::
    .string "CASSIE$"

gNameChoice_Rey::
    .string "REY$"

gNameChoice_Seda::
    .string "SEDA$"

gNameChoice_Kiko::
    .string "KIKO$"

gNameChoice_Mina::
    .string "MINA$"

gNameChoice_Norie::
    .string "NORIE$"

gNameChoice_Sai::
    .string "SAI$"

gNameChoice_Momo::
    .string "MOMO$"

gNameChoice_Suzi::
    .string "SUZI$"

gControlsGuide_Text_Intro::
    .string "The various buttons will be explained in\n"
    .string "the order of their importance.$"

gControlsGuide_Text_DPad::
    .string "Moves the main character.\n"
    .string "Also used to choose various data\n"
    .string "headings.$"

gControlsGuide_Text_AButton::
    .string "Used to confirm a choice, check\n"
    .string "things, chat, and scroll text.$"

gControlsGuide_Text_BButton::
    .string "Used to exit, cancel a choice,\n"
    .string "and cancel a mode.$"

gControlsGuide_Text_StartButton::
    .string "Press this button to open the\n"
    .string "MENU.$"

gControlsGuide_Text_SelectButton::
    .string "Used to shift items and to use\n"
    .string "a registered item.$"

gControlsGuide_Text_LRButtons::
    .string "If you need help playing the\n"
    .string "game, or on how to do things,\n"
    .string "press the L or R Button.$"

gOakSpeech_Text_AskPlayerGender::
    .string "Now tell me. Are you a boy?\n"
    .string "Or are you a girl?$"

gPikachuIntro_Text_Page1::
    .string "In the world which you are about to\n"
    .string "enter, you will embark on a grand\n"
    .string "adventure with you as the hero.\n"
    .string "\n"
    .string "Speak to people and check things\n"
    .string "wherever you go, be it towns, roads,\n"
    .string "or caves. Gather information and\n"
    .string "hints from every source.$"

gPikachuIntro_Text_Page2::
    .string "New paths will open to you by helping\n"
    .string "people in need, overcoming challenges,\n"
    .string "and solving mysteries.\n"
    .string "\n"
    .string "At times, you will be challenged by\n"
    .string "others and attacked by wild creatures.\n"
    .string "Be brave and keep pushing on.$"

gPikachuIntro_Text_Page3::
    .string "Through your adventure, we hope\n"
    .string "that you will interact with all sorts\n"
    .string "of people and achieve personal growth.\n"
    .string "That is our biggest objective.\n"
    .string "\n"
    .string "Press the A Button, and let your\n"
    .string "adventure begin!$"

gOakSpeech_Text_WelcomeToTheWorld::
    .string "Hello, there!\n"
    .string "Glad to meet you!\p"
    .string "Welcome to the world of POKéMON!\p"
    .string "My name is MYRTLE.\p"
    .string "People affectionately refer to me\n"
    .string "as the POKéMON PROFESSOR.\p$"

gOakSpeech_Text_ThisWorld::
    .string "This world…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
    .string "…is inhabited far and wide by\n"
    .string "creatures called POKéMON.\p$"

gOakSpeech_Text_IStudyPokemon::
    .string "For some people, POKéMON are pets.\n"
    .string "Others use them for battling.\p"
    .string "As for myself…\p"
    .string "I study POKéMON as a profession.\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
    .string "But first, tell me a little about\n"
    .string "yourself.\p$"

gOakSpeech_Text_AdventureSetupPreface::
    .string "Before we begin, let's set a couple\n"
    .string "of adventure options.\p$"

gOakSpeech_Text_LevelCapQuestion::
    .string "Would you like to use LEVEL CAPS?\n"
    .string "NO is the easier option.\p$"

gOakSpeech_Text_BattleStyleQuestion::
    .string "Choose your BATTLE STYLE.\n"
    .string "SHIFT is the easier option.\p$"

gOakSpeech_Text_AdventureSetupCanChangeLater::
    .string "You can change these options later\n"
    .string "in the OPTIONS menu.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
    .string "Let's begin with your name.\n"
    .string "What is it?\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
    .string "Right…\n"
    .string "So your name is {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName::
    .string "This is your friend from the\n"
    .string "orphanage.\p"
    .string "You've known each other since you\n"
    .string "were babies.\p"
    .string "…Erm, what was his name now?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
    .string "Your orphanage friend's name,\n"
    .string "what was it now?$"

gOakSpeech_Text_YourSecondRivalsNameWhatWasIt::
    .string "And that town kid's name,\n"
    .string "what was it now?$"

gOakSpeech_Text_ConfirmRivalName::
    .string "…Er, was it {RIVAL}?$"

gOakSpeech_Text_ConfirmRival2Name::
    .string "…Er, was it {RIVAL2}?$"

gOakSpeech_Text_RememberRivalsName::
    .string "That's right! His name is {RIVAL}!\p"
    .string "Now then… There's that kid from town\n"
    .string "who always tries to prove he's\n"
    .string "better than you.\p$"

gOakSpeech_Text_RememberRival2Name::
    .string "Right! That kid's name is {RIVAL2}!\p$"

gOakSpeech_Text_LetsGo::
    .string "{PLAYER}!\p"
    .string "Your very own POKéMON legend is\n"
    .string "about to unfold!\p"
    .string "{RIVAL} and {RIVAL2} are waiting\n"
    .string "for you out there!\p"
    .string "A world of dreams and adventures\n"
    .string "with POKéMON awaits! Let's go!$"
