
HavenTown_Orphanage_Text_IrisCommon::
    .string "I found a pretty blue feather in the\n"
    .string "yard today.\pIt made my whole morning.$"

HavenTown_Orphanage_Text_IrisMid::
    .string "Teo pretends the yard is a jungle,\p"
    .string "so I made him a flower badge.$"

HavenTown_Orphanage_Text_IrisRare::
    .string "When I grow up, I want a team that's\n"
    .string "strong and gentle.\pLike Mrs. Marina.$"

HavenTown_Orphanage_Text_TeoCommon::
    .string "I built a fort behind the old fence!\p"
    .string "It's secret. Well... mostly secret.$"

HavenTown_Orphanage_Text_TeoMid::
    .string "{RIVAL} is the best!\p"
    .string "One day I will be as strong as him.$"

HavenTown_Orphanage_Text_TeoRare::
    .string "Sometimes I act brave so the other\n"
    .string "kids don't get scared.\pDon't tell anyone!$"
