HavenTown_Orphanage_Text_Mailbox::
    .string "HAVEN TOWN'S ORPHANAGE\n"
    .string "Run by Mrs. Marina$"

HavenTown_Orphanage_Text_Zigzagoon::
    .string "Kee-kiiiiii!$"

HavenTown_Orphanage_Text_IrisCommon::
    .string "I help clean every day.\p"
    .string "Mrs. Marina says it builds grit!$"

HavenTown_Orphanage_Text_IrisMid::
    .string "Teo races me to the stairs.\p"
    .string "I usually win!$"

HavenTown_Orphanage_Text_IrisRare::
    .string "One day, I'll raise a team\l"
    .string "that protects this town!$"
