HavenTown_Orphanage_2F_Text_Kangaskhan::
    .string "Khaaaaaa!$"

HavenTown_Orphanage_2F_Text_ChoresSign::
    .string "It's a list of chores for the week\n"
    .string "Every kid has one.$"

HavenTown_Orphanage_2F_Text_ThomasFact1::
    .string "Did you know? BUTTERFREE can taste\n"
    .string "with its feet!$"

HavenTown_Orphanage_2F_Text_ThomasFact2::
    .string "Did you know? VULPIX are born with\n"
    .string "one white tail.\pIt splits as they grow!$"

HavenTown_Orphanage_2F_Text_ThomasFact3::
    .string "Did you know? MAGIKARP can survive\n"
    .string "in really dirty water.\pThat's amazing!$"

HavenTown_Orphanage_2F_Text_ThomasFact4::
    .string "Did you know? SLOWPOKE fish by\n"
    .string "dangling their tails.\pSmart and lazy!$"

HavenTown_Orphanage_2F_Text_ThomasFact5::
    .string "Did you know? KANGASKHAN babies stay\n"
    .string "in the pouch for safety.$"

HavenTown_Orphanage_2F_Text_ThomasFact6::
    .string "Did you know? PIKACHU shock each\n"
    .string "other to greet friends.\pAt least, that's my theory!$"

HavenTown_Orphanage_2F_Text_MarinaCallsPlayerDownstairs::
    .string "Mrs. Marina: {PLAYER}!\n"
    .string "Come downstairs right away, please!$"

HavenTown_Orphanage_2F_Text_ThomasMarinaWaitingDownstairs::
    .string "Mrs. Marina is waiting for you\n"
    .string "downstairs.\pYou should go now.$"
