OldManHouse_Text_MrRupertBeforeQuest::
    .string "Mr. Rupert: Hm?\n"
    .string "Lovely weather for a walk.$"

OldManHouse_Text_MrRupertWife_NotStarted::
    .string "My husband takes little walks\n"
    .string "to clear his head.$"

OldManHouse_Text_MrRupertWife_ParkHint::
    .string "Oh, you're looking for my husband?\p"
    .string "Mr. Rupert went for a walk in\n"
    .string "the park to the east.$"

OldManHouse_Text_MrRupertWife_AfterQuest::
    .string "Rupert mentioned meeting you in\n"
    .string "the park.\pHe seemed thoughtful.$"
