HavenTown_Text_TownSign::
    .string "HAVEN TOWN\n"
    .string "A Place To Call Home.$"

HavenTown_Text_Rival2Mailbox::
    .string "{RIVAL2}'s house$"

HavenTown_Text_PressStartToOpenMenu::
	.string "TRAINER TIPS\p"
	.string "Press START to open the MENU!$"

HavenTown_Text_ParkSign::
    .string "HAVEN TOWN PARK\n"
    .string "Come and relax.$"

HavenTown_Text_CedricsMom::
    .string "Cedric is waiting for someone\n"
    .string "important.\pSo don't waste my time.$"

HavenTown_Text_ParkGateStop::
    .string "I should deliver Mrs. Marina's\n"
    .string "envelope to one of the houses first.$"

HavenTown_Text_MrRupertPark::
    .string "Mr. Rupert: Hmm... I see.\p"
    .string "Leave that message with me.\n"
    .string "I'll take care of it.$"

HavenTown_Text_PotionItemGone::
    .string "There's nothing here.$"

HavenTown_Text_LeaveTownBlocked::
    .string "I'm not authorized to leave town\n"
    .string "without Mrs. Marina's permission.$"

HavenTown_Text_MyrtleAsksDirections::
    .string "Professor: Oh! Excuse me.\p"
    .string "Can you point me to Haven Town?$"

HavenTown_Text_GruntsAmbushMyrtle::
    .string "Team Ashen Grunt: Hand over your\n"
    .string "rare POKéMON, Professor!$"

HavenTown_Text_MyrtleUseOnePokemon::
    .string "The professor dropped some pokeballs!$"

HavenTown_Text_MyrtleRepeatInstruction::
    .string "Professor: Hurry!\n"
    .string "Use one of those POKéMON!$"

HavenTown_Text_GruntGoAway::
    .string "Get lost, kid.\n"
    .string "This doesn't concern you.$"

HavenTown_Text_GruntsBlockPark::
    .string "Those Team Ashen grunts are\n"
    .string "blocking the park entrance.$"

HavenTown_Text_ChooseStarterConfirm::
    .string "Do you want this POKéMON?$"

HavenTown_Text_ReceivedStarter::
    .string "{PLAYER} received {STR_VAR_1}!$"

HavenTown_Text_GruntBattleStart::
    .string "Team Ashen Grunt: Bad move, kid.\n"
    .string "You don't cross Team Ashen!$"

HavenTown_Text_GruntBattleDefeat::
    .string "Team Ashen Grunt: Tch... You'll\n"
    .string "regret crossing Team Ashen!$"

HavenTown_Text_GruntsRetreat::
    .string "Team Ashen Grunt: We got beaten by\n"
    .string "a kid... Pull back!$"

HavenTown_Text_MyrtleThanks::
    .string "Professor: Thank you, kid.\p"
    .string "For that courage, the POKéMON is\n"
    .string "yours to keep.$"

HavenTown_Text_MyrtlePresentation::
    .string "Professor: My name is Myrtle,\n"
    .string "pleased to meet you.\p"
    .string "I was supposed to give his first\n"
    .string "POKéMON to a kid in Haven Town.\p"
    .string "Do you know {RIVAL2}?$"

HavenTown_Text_MyrtleComeWithMe::
    .string "Fantastic!\p"
    .string "Please, come with me and show\n"
    .string "the way.$"

HavenTown_Text_MyrtleAfterEscort::
    .string "Prof. Myrtle: This should be the\n"
    .string "house. Thank you, {PLAYER}.$"

HavenTown_Text_RupertBadPeople::
    .string "Mr. Rupert: Those are bad people.\n"
    .string "Stay sharp, child.$"

HavenTown_Text_MrRupertAfterQuest::
    .string "Mr. Rupert: You've done your part.\n"
    .string "Now keep moving.$"
