HavenTown_Text_TownSign::
    .string "HAVEN TOWN\n"
    .string "A Place To Call Home.$"

HavenTown_Text_Rival2Mailbox::
    .string "{RIVAL2}'s house$"

HavenTown_Text_PressStartToOpenMenu::
	.string "TRAINER TIPS\p"
	.string "Press START to open the MENU!$"

HavenTown_Text_ParkSign::
    .string "HAVEN TOWN PARK\n"
    .string "Come and relax.$"

HavenTown_Text_CedricsMom::
    .string "Cedric is waiting for someone\n"
    .string "important.\pSo don't waste my time.$"

HavenTown_Text_ParkGateStop::
    .string "I should deliver Mrs. Marina's\n"
    .string "envelope to one of the houses first.$"

HavenTown_Text_MrRupertPark::
    .string "Mr. Rupert: Hmm... I see.\p"
    .string "Leave that message with me.\n"
    .string "I'll take care of it.$"

HavenTown_Text_PotionItemGone::
    .string "There's nothing here.$"
