TestingGrounds_Text_FatManTakeThisTM::
    .string "I found a useful TM while training\n"
    .string "my POKéMON.\p"
    .string "Take TM35.\n"
    .string "A CHARMANDER can use it.$"

TestingGrounds_Text_ReceivedTM35FromFatMan::
    .string "{PLAYER} received TM35\n"
    .string "from the man.$"

TestingGrounds_Text_FatManExplainsTM::
    .string "TM35 is FLAMETHROWER.\p"
    .string "Teach it to a fire-type POKéMON,\n"
    .string "like CHARMANDER.$"

TestingGrounds_Text_FatManNoRoomForTM::
    .string "You don't have room for this.$"

TestingGrounds_Text_FatManAlreadyGaveTM::
    .string "Train your POKéMON well.\p"
    .string "A strong CHARMANDER makes this TM\n"
    .string "shine.$"
